### ISSUE TITLE
False link to lecture webpage

### ISSUE THREAD

**Issue by MariusHerget** [scalable-infrastructure/exercise-students-2018#1]
Wrong link on the [webpage](http://www.nm.ifi.lmu.de/teaching/Vorlesungen/2018ss/data-analytics/):

Current (wrong): https://github.com/scalable-infrastructure/exercise-2018
Correct:  https://github.com/scalable-infrastructure/exercise-students-2018

**Comment by drelu** [comment]
fixed. Danke!

**Comment by MariusHerget** [comment]
@drelu Ebenso sind alle links im  03_MapReduce notebook falsch
